### ISSUE TITLE
Adicionar botão excluir para os contents

### ISSUE THREAD

**Issue by JoaoPauloBorges** [JoaoPauloBorges/angular-blitzlcc#5]
Atualmente os conteúdos gerados na plataforma só possuem a opção de criação e update, é necessário que se disponibilize também a opção de remover para:
* Pesquisador
* Topico
* Paper
* Post

**Comment by JoaoPauloBorges** [comment]
PS. Utilizar uma única branch para cada issue 😉🍃

**Comment by rafaelgomesxyz** [comment]
Como lidar com remoção de tópicos e pesquisadores associados a um paper? Mostrar um dialog indicando a dependência e não permitir a remoção?

**Comment by JoaoPauloBorges** [comment]
Bom, No caso de topico, é cascade, porém com alerta em modal e clique de confirmação. 
No caso de Researcher, não tem problema existir paper sem pesquisador (o paper tem o field de referências pra isso, e nem todos os pesquisadores da referência vão ser cadastrados no app, somente aqueles que os adms acharem pertinentes), porém tem que limpar as referencias do pesquisador dos documentos que o continham.
Inclusive, lá no form do Paper, pode retirar a validation de obrigatoriedade de preencher um pesquisador, as outras validações permanecem.
No caso dos  posts, o campo do Author é textual, então é só apagar mesmo.
