### ISSUE TITLE
Sugestão: botão para criar novos itens na página de listagem

### ISSUE THREAD

**Issue by rafaelgomesxyz** [JoaoPauloBorges/angular-blitzlcc#7]
Não seria mais interessante ao invés de ter os links de registration na sidebar, ter um botão para criar novos itens na página de listagem dos itens, perto da barra de filtrar?

Exemplo:

![](https://i.imgur.com/P3ME2lJ.png)

**Comment by JoaoPauloBorges** [comment]
Pode implementar rafael, a diferença é que vamos aumentar o caminho do registro em 1 click (Desktop serão 2 clicks, mobile serão 3 clicks). Porém n acho que seja tão traumático. Apenas implemente o novo botão, não retire os da sidebar, que ai podemos verificar o que fica mais usual em questão de navegação. Como é só adicionar botão com link, é fácil retirar um ou o outro depois.

**Comment by JoaoPauloBorges** [comment]
@rafaelgssa tá conseguindo rodar a aplicação localmente com npm run dev?

**Comment by rafaelgomesxyz** [comment]
Sim, tá normal agora com o proxy.
